#!/usr/bin/env bash

APP_NAME=svelte-app
IMAGE_NAME=svelte-project
CONTAINER_NAME=svelte-project
#USER_NAME=dev
USER_NAME=node
CONTAINER_DIR=/home/$USER_NAME/$APP_NAME

# Build a Docker image using the Dockerfile in the current directory.
docker build -t $IMAGE_NAME .

# Get the image id.
imageId=`docker images $IMAGE_NAME --format "{{.ID}}"`
echo Docker image id is $imageId

# Stop the running container if it exists.
# It will be automatcally deleted because
# the --rm option was used when it was created.
docker ps --quiet --filter "name=$CONTAINER_NAME" | grep --quiet . && docker stop $CONTAINER_NAME

# Delete dangling images and stopped containers..
docker system prune --force

mkdir $APP_NAME

# Run the image inside a container.
docker run \
  --detach \
  --interactive \
  --name "$CONTAINER_NAME" \
  --publish 5000:5000 \
  --rm \
  --tty \
  # The next line prevents "npm degit" from working!  Why?
  --volume $SVELTE_DIR/svelte-docker/container:/home/$USER_NAME \
  "$IMAGE_NAME"
#--volume ~/$APP_NAME:/home/$USER_NAME/$APP_NAME \
#--mount source=$APP_NAME,target=/home/$USER_NAME/$APP_NAME \

# Get the container id.
containerId=`docker ps --last 1 --quiet`
echo Docker container id is $containerId

# Open a shell inside the container.
echo Opening a shell inside the container ...
docker exec -it $containerId /bin/bash

